#MCDealer Plugin Settings


#Port of the Web Server
web-server-port: 8080
#How often should the shop data be updated? (in ticks: 20T = 1 second)
UpdateInterval: 300
#Currency symbol that is displayed on the website
currencySymbol: Ê—
#Position of the Currency Symbol (before/after)
currencySymbolPosition: after
#Default language of the website
defaultLanguage: de


#Don't change anything below!
configversion: 1
webfilesversion: 1