#MCDealer Plugin Settings


#Port of the Web Server
web-server-port: 8080
#How often should the shop data be updated? (in ticks: 20T = 1 second || Default: 6000 = 5 minutes)
UpdateInterval: 6000
#Currency symbol that is displayed on the website
currencySymbol: Ê—
#Position of the Currency Symbol (before/after)
currencySymbolPosition: after
#Default language of the website
defaultLanguage: en


#Don't change anything below!
configversion: 2
webfilesversion: 2