name: MCDealer
authors: [CaptainGummiball, Vollmondheuler]
description: MCDealer hosts an internal web server to display Villagermarket's shop data
version: dev1.0.2
main: org.mcdealer.mcdealer.MCDealer
softdepend: [VillagerMarket]
api-version: '1.20'
load: POSTWORLD