name: MCDealer
authors: [CaptainGummiball, Vollmondheuler]
description: MCDealer hosts an internal web server to display Villagermarket's shop data
version: dev1.0.3
main: org.mcdealer.mcdealer.MCDealer
softdepend: [VillagerMarket]
api-version: '1.20'
load: POSTWORLD

commands:
  mcdealer:
    description: Hauptcommand für den MCDealer.
    usage: /mcdealer <hideshop|showshop|restart>
    permission: mcdealer.use

permissions:
  mcdealer.use:
    description: Allows access to the /mcdealer command.
    default: op
  mcdealer.hideshop:
    description: Allows hiding shops with /mcdealer hideshop.
    default: op
  mcdealer.showshop:
    description: Show shops again with /mcdealer showshop.
    default: op
  mcdealer.restart:
    description: Allows restarting the web server with /mcdealer restart.
    default: op